### PR TITLE
Add zsh support.

### PR DESCRIPTION
**Pull request by haosdent**
Use offset skip zsh timestamp.

### CODE REVIEW

**Comment by tbabej** [comment]
Could you please add some comments so that the logic is easy to follow for person not that familiar with zsh?

**Comment by haosdent** [comment]
Yeah.

**Comment by haosdent** [comment]
For zsh history file, it looks like this:
```
: 1420549651:0;ls /tmp/b
: 1420549680:0;touch /tmp/c
: 1420549686:0;ln -s /tmp/c /tmp/b
```
[:][blank][unix_timestamp][:][0][;]

Because unix timestamp 9999999999 is 2289, we could skip 15 chars in every zsh history item.

**Comment by haosdent** [comment]
Or you mean I should add this to source file?

**Comment by tbabej** [comment]
Yes, please. The pull request might get lost in the depths of time, but the comments in the source will not perish.

**Comment by haosdent** [comment]
Thank you. I see :+1:

**Comment by haosdent** [comment]
@tbabej Please review this again, I am no a native English speaker, maybe have some problems in comments.

**Comment by tbabej** [comment]
The comments look just fine to me, thanks. I'll leave code review to @dvorka .

**Comment by haosdent** [comment]
Thx.

**Comment by dvorka** [comment]
@haosdent thank you for your contribution - nice work!

**Comment by Heart1010** [comment]
To bind ```CTRL+R``` in zsh to hh we have to add this line to ~/.zshrc
```bash
bindkey -s '^R' '^Ahh ^M'
```
Should we add that info to https://github.com/dvorka/hstr/blob/master/CONFIGURATION.md#zsh-history-settings ?

**Comment by haosdent** [comment]
yeah, I use `bindkey -s "\C-r" "\C-ahh \C-j"` in zsh.

**Comment by Heart1010** [comment]
It would be perfect if hstr would recognize the used shell when using the command ```hh --show-configuration``` and output the correct lines for that used shell.

**Pull request merged**
