### PR TITLE
164: Workaround for missing TIOCSTI ioctl call on Cygwin.

### PR DESCRIPTION
**Pull request by jmiserez**
Based on the changes by @riedel, slightly cleaned up and minimized:
https://github.com/dvorka/hstr/commit/6bcdcc8ad36ced8f2acef68be1b477b366607d10
https://github.com/dvorka/hstr/commit/01713eb4c22a8b57fd79428a6b5aff0a56011f98

This removes the fix from https://github.com/dvorka/hstr/commit/79781c138b972f553303d2b6d045ae215391a014 as that only fixes the compilation errors, but the function is not actually implemented in Cygwin.

See https://github.com/dvorka/hstr/issues/164 for discussion.

### CODE REVIEW

**Comment by jmiserez** [comment]
Hm, I think it would be cleaner to not use temporary files but instead use a bash variable. I'll change it and update this PR tomorrow.

**Comment by jmiserez** [comment]
I added another commit, it now uses a variable to capture stderr instead of a temporary file. Method is the same as here: https://stackoverflow.com/a/6317938/202504

Note that the method from here (http://sebthom.de/158-bash-capturing-stderr-variable/) also works, but I didn't want to add a dependency on `tee`.

Tested and works on my Cygwin machine, I think it should be safe to merge as it only affects Cygwin installs, which otherwise don't work at all.

**Comment by dvorka** [comment]
@jmiserez this is excellent work!  Thank you finding the workaround and nice implementation!

**Comment by dvorka** [comment]
BTW, I guess that this might be also solution for #186!

**Comment by jmiserez** [comment]
@dvorka Thanks, but credit goes to @riedel for most of it.

**Pull request merged**
