### PR TITLE
docs: Add installation instructions for Fedora based systems

### PR DESCRIPTION
**Pull request by tbabej**
I created a copr repo (similiar to Ubuntu's PPA) for hstr. Available for Fedora 20-22, RHEL/CentOS/Scientific Linux 6-7.

### CODE REVIEW

**Comment by dvorka** [comment]
Cool! Appreciate it - thanks!

**Comment by dvorka** [comment]
BTW, is there a way to automate release process through this repo?

**Comment by tbabej** [comment]
Yeah, I guess it would be possible. Both Copr and Github do have APIs, but I guess it would be too much work given that manual changes still need to me made :) For proper package maintainence, it's a good guideline to keep updated info & changelog in the package, which means manually editing the spec file anyway.

If you're worried about packages in the wild falling behind the releases, worry not. I watch this repo, so it should not happen. I guess the best way to prevent this would be tagging me in the "Release version X" github issue after the release has been done.

**Comment by dvorka** [comment]
>  I guess the best way to prevent this would be tagging me in the "Release version X" github issue after the release has been done.

Great! This is exactly what I meant ;)

**Pull request merged**
